import 'package:get/get.dart';

class CLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'idHint': 'Student ID',
          'login': 'Login',
          'passwordHint': 'Password',
          'forgetPass': 'Forget Password?',
          'welcome': 'Welcome to School Information Management System',
          'userName': 'John Snow',
          'userSub': 'Class 2B | roll no 20',
          'titleAcademics': 'Academics',
          'courseResult': 'Course result',
          'attendance': 'Attendance',
          'timeTable': 'Time table',
          'library': 'Library',
          'notice': 'Notice',
          'setting': 'Setting',
          'settingSubtitle': 'Personalize your experience',
          'message': 'Message',
          'messageSubtitle': 'Stay connected',
          'parentalService': 'Parental Service',
          'course': 'Courses',
          'search': 'Search',
          'myCourse': 'My course',
          'absentDates': 'Absent Dates',
          'addAccount': 'Add account',
          'profile': 'Profile',
          'examResult': 'Exam result',
          'about': 'About',
          'home': 'Home',
          'notification': 'Notification',
          'generalSettings': 'General Settings',
          'language': 'Languages',
          'darkMode': 'Dark Mode',
          'pushNotification': 'Push Notifications',
          'accountSettings': 'Account Settings',
          'changePassword': 'Change Password',
          'updateProfile': 'Update Profile',
          'academicSettings': 'Academic Settings',
          'academicYear': 'Academic Year',
          'classGrade': 'Class',
          'appInformation': 'App Information',
          'privacyPolicy': 'Privacy Policy',
          'termOfServices': 'Term of Service',
          'selectPreferredLanguage': 'Select your preferred language',
          'toggleDarkMode': 'Toggle dark mode for better night viewing',
          'managePushNotification': 'Manage your push notification preferences',
          'updateYourPassword': 'Update your password for security reasons',
          'editYourPersonalAndContact':
              'Edit your personal and contact information',
          'reviewTermAndPolicy': 'Review the terms of service',
          'learnMoreAbout': 'Learn more about our app',
          'dateOfAdmission': 'Date of Admission',
          'fatherName': 'Father name',
          'motherName': 'Mother name',
          'dateOfBirth': 'Date of birth',
          'age': 'Age',
          'parentPhone': 'Parent Phone',
          'address': 'Address',
          'phoneNumber': 'Phone Number',
          'gallery': 'Gallery',
          'unauthorizedError': 'User not authenticated',
          'gradeReport': 'Grade report',
          'personalInformation': 'Personal Information',
          'parentInformation': "Parent Information",
          'academicInformation': "Academic Information",
          'section': "Section"
        },
        'am_ET': {
          'idHint': 'የተማሪ መታወቂያ',
          'login': 'ግባ',
          'passwordHint': 'የይለፍ ቃል',
          'forgetPass': 'የይለፍ ቃል ረሳህ?',
          'welcome': 'እንኳን ደህና መጡ ወደ ትምህርት ቤት መረጃ አስተዳደር ሥርዓት',
          'userName': 'ጆን ስኖው',
          'userSub': 'ክፍል 2ቢ | የምዝገባ ቁጥር 20',
          'titleAcademics': 'አካዳሚ',
          'courseResult': 'የትምህርት ውጤት',
          'attendance': 'እንቅስቃሴ',
          'timeTable': 'የጊዜ ሰሌዳ',
          'library': 'ቤተ መጻህፍት',
          'notice': 'ማስታወቂያ',
          'setting': 'ቅንብር',
          'settingSubtitle': 'ተሟላ ማረፊያ',
          'message': 'መልእክት',
          'messageSubtitle': 'ጋር እንቆብቆብ ይቀጥሉ',
          'parentalService': 'የወላጆች አገልግሎት',
          'course': 'ኮርስ',
          'search': 'ፈልግ',
          'myCourse': 'የእኔ ኮርስ',
          'absentDates': 'የጥፋት ቀናት',
          'addAccount': 'መለያ አክል',
          'profile': 'መገለጫ',
          'examResult': 'የፈተና ውጤት',
          'about': 'ስለ',
          'home': 'መነሻ ገጽ',
          'notification': 'ማሳወቂያ',
          'generalSettings': 'አጠቃላይ ቅንብሮች',
          'language': 'ቋንቋዎች',
          'darkMode': 'ጨለማ ሁነታ',
          'pushNotification': 'እንቆቅኝ ማሳወቂያዎች',
          'accountSettings': 'የመለያ ቅንብሮች',
          'changePassword': 'የይለፍ ቃል ቀይር',
          'updateProfile': 'መገለጫ አዘምን',
          'academicSettings': 'አካዳሚ ቅንብሮች',
          'academicYear': 'የትምህርት ዓመት',
          'classGrade': 'ክፍል/ደረጃ',
          'appInformation': 'የመተግበሪያ መረጃ',
          'privacyPolicy': 'የቅጂ አመክሮች ደረጃ',
          'termOfServices': 'የአገልግሎት ውሎች',
          'selectPreferredLanguage': 'እባክዎን የተመረጡትን ቋንቋ ይምረጡ',
          'toggleDarkMode': 'ለበለይ ዕንቅስቃሴ ምርጫ ባለበት ጥምረት ያደርጉ',
          'managePushNotification': 'የእንቆቅኝ ማሳወቂያዎችን ይቆጣጠሩ',
          'updateYourPassword': 'ለደህንነት ምክንያቶች የይለፍ ቃልዎን ያዘምኑ',
          'editYourPersonalAndContact': 'የግል እና የተገኘበት መረጃዎን ያርትዑ',
          'reviewTermAndPolicy': 'የአገልግሎት ውሎችን ያርትዑ',
          'learnMoreAbout': 'ስለ መተግበሪያው በጥቂቱ ተረድተው ይማሩ',
          'dateOfAdmission': 'የመግቢያ ቀን',
          'fatherName': 'የአባት ስም',
          'motherName': 'የእናት ስም',
          'dateOfBirth': 'የትውልድ ቀን',
          'age': 'እድሜ',
          'parentPhone': 'የወላጅ ስልክ',
          'address': 'አድራሻ',
          'phoneNumber': 'ስልክ ቁጥር',
        },
        'om_ET': {
          'idHint': 'ID Barataa',
          'login': 'Seeni',
          'passwordHint': 'Jecha Iccitii',
          'forgetPass': 'Jecha Iccitii Dagateetta?',
          'welcome':
              'Baga Nagaan Gara Sirnaa Odeeffannoo Mana Barumsa Bulchiinsaatti Dhuftan',
          'userName': 'John Snow',
          'userSub': 'Kutaa 2B | lakkoofsa galmee 20',
          'titleAcademics': 'Barnoota',
          'courseResult': 'Bu’aa koo',
          'attendance': 'Argamuu',
          'timeTable': 'Fuula Yeroo',
          'library': 'Galma Kitaabota',
          'notice': 'Beeksisa',
          'setting': 'Seera',
          'settingSubtitle': 'Safartuu xiinsammuu keessan qopheessaa',
          'message': 'Ergaa',
          'messageSubtitle': 'Wal qunnamtii irra jiraadhaa',
          'parentalService': 'Tajaajila Maatii',
          'course': 'Koorsoota',
          'search': 'Barbaadi',
          'myCourse': 'Koorsoo koo',
          'absentDates': 'Guyyoota Dhaabbataa',
          'addAccount': 'Galmee dabaluu',
          'profile': 'Konkolaataa',
          'examResult': 'Bu’aa Qormaataa',
          'about': 'Waa’ee',
          'home': 'Mana',
          'notification': 'Beeksisaa',
          'generalSettings': 'Karoora Guutuu',
          'language': 'Afaanota',
          'darkMode': 'Haalata Dukkanaa',
          'pushNotification': 'Beeksisa Dhiibbaa',
          'accountSettings': 'Seerota Galmee',
          'changePassword': 'Jecha Iccitii Jijjiiru',
          'updateProfile': 'Konkolaataa Haaromsuu',
          'academicSettings': 'Seerota Barnoota',
          'academicYear': 'Waggaa Barnootaa',
          'classGrade': 'Kutaa/Darajaa',
          'appInformation': 'Odeeffannoo App',
          'privacyPolicy': 'Heera Biyyaalessaa',
          'termOfServices': 'Seerota Tajaajilaa',
          'selectPreferredLanguage': 'Afaan Filatame Filadhu',
          'toggleDarkMode': 'Haalata dukkanaa fooyyeessuuf toogle godhi',
          'managePushNotification': 'Filannoo Beeksisa Dhiibbaa qopheessi',
          'updateYourPassword': 'Sababa nageenyaaf jecha iccitii kee haaromsi',
          'editYourPersonalAndContact':
              'Odeeffannoo kee fi qunnamtii kee sirreessi',
          'reviewTermAndPolicy':
              'Seerota Tajaajilaa fi Heera Biyyaalessaa ilaali',
          'learnMoreAbout': 'Waa’ee app keenya baradhu',
          'passwordRecovery': 'Sirreeffama Jecha Iccitii',
          'birthDate': 'Guyyaa Dhalootaa',
          'dateOfAdmission': 'Guyyaa Galmaa\'uu',
          'fatherName': 'Maqaa Abbaa',
          'motherName': 'Maqaa Haadha',
          'dateOfBirth': 'Guyyaa Dhalootaa',
          'age': 'Umrii',
          'parentPhone': 'Lakkoofsa Bilbilaa Maatii',
          'address': 'Teessoo',
          'phoneNumber': 'Lakkoofsa Bilbilaa',
        },
      };
}
